import { BREAKPOINTS_QUERY_NAMES } from './constants'

const BREAKPOINTS_QUERY = {
    [BREAKPOINTS_QUERY_NAMES.XS]: 0,
    [BREAKPOINTS_QUERY_NAMES.SM]: 576,
    [BREAKPOINTS_QUERY_NAMES.MD]: 768,
    [BREAKPOINTS_QUERY_NAMES.LG]: 1200,
    [BREAKPOINTS_QUERY_NAMES.XL]: 1500,
    [BREAKPOINTS_QUERY_NAMES.XXL]: 2000,
};
  
  export default BREAKPOINTS_QUERY;
  